[package]
name = "xtask"
description = "xtasks for the Oxipng project: https://github.com/matklad/cargo-xtask"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cargo_metadata = "0.23.1"
clap = { version = "4.6.6", features = ["string"] }
clap_mangen = "0.3.3"
parse-size = "1.1.0"
tz-rs = "0.7.3"
