[package]
name = "xtask"
description = "xtasks for the Oxipng project: https://github.com/matklad/cargo-xtask"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = "4.5.21"
clap_mangen = "0.2.24"
