# Remove this if targeting AArch64 from an AArch64 Linux box
[target.'cfg(all(target_os = "linux", target_arch = "aarch64"))']
runner = 'qemu-aarch64'

[target.aarch64-unknown-linux-gnu]
linker = 'aarch64-linux-gnu-gcc'

[target.aarch64-unknown-linux-musl]
linker = 'aarch64-linux-musl-gcc'
